In [2]:
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


# Locate the project root
current_folder = Path.cwd()

project_root = (
    current_folder.parent
    if current_folder.name == "notebooks"
    else current_folder
)

# Build the path to the raw heart disease dataset
data_path = (
    project_root
    / "data"
    / "raw"
    / "heart_disease_uci.csv"
)

# Verify the dataset path
print(
    "Dataset path:",
    data_path
)

print(
    "File exists:",
    data_path.exists()
)

# Load the raw dataset
heart_df = pd.read_csv(
    data_path
)

# Display the basic dataset information
print(
    "\nDataset shape:",
    heart_df.shape
)

print(
    "\nColumn names:"
)

print(
    heart_df.columns.tolist()
)

print(
    "\nData types:"
)

print(
    heart_df.dtypes
)

print(
    "\nMissing values by column:"
)

print(
    heart_df.isnull()
    .sum()
    .sort_values(
        ascending=False
    )
)

print(
    "\nDuplicated rows:",
    heart_df.duplicated().sum()
)

print(
    "\nTarget distribution:"
)

print(
    heart_df["num"]
    .value_counts(
        dropna=False
    )
    .sort_index()
)

print(
    "\nRecords by dataset source:"
)

print(
    heart_df["dataset"]
    .value_counts(
        dropna=False
    )
)

display(
    heart_df.head()
)

Dataset path: d:\1. My Files in Collage\5th Level\AI\Multi_Disease_ML_System\data\raw\heart_disease_uci.csv
File exists: True

Dataset shape: (920, 16)

Column names:
['id', 'age', 'sex', 'dataset', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalch', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'num']

Data types:
id            int64
age           int64
sex             str
dataset         str
cp              str
trestbps    float64
chol        float64
fbs          object
restecg         str
thalch      float64
exang        object
oldpeak     float64
slope           str
ca          float64
thal            str
num           int64
dtype: object

Missing values by column:
ca          611
thal        486
slope       309
fbs          90
oldpeak      62
trestbps     59
exang        55
thalch       55
chol         30
restecg       2
cp            0
dataset       0
id            0
age           0
sex           0
num           0
dtype: int64

Duplicated rows: 0

Target distribution:
num
0    411
1    265
2    109
3    107
4     28
Name: count, dtype: int64

Records by dataset source:
dataset
Cleveland        304
Hungary          293
VA Long Beach    200
Switzerland      123
Name: count, dtype: int64

,id,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,num
0,1,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
1,2,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,2
2,3,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
3,4,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
4,5,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0

In [3]:
# Create a binary heart disease target
heart_binary_target = (
    heart_df["num"] > 0
).astype(int)

# Display the binary target distribution
binary_target_summary = pd.DataFrame(
    {
        "Count": (
            heart_binary_target
            .value_counts()
            .sort_index()
        ),
        "Percentage": (
            heart_binary_target
            .value_counts(
                normalize=True
            )
            .sort_index()
            .mul(100)
            .round(2)
        )
    }
)

binary_target_summary.index = [
    "No heart disease",
    "Heart disease present"
]

print(
    "Binary target distribution:"
)

display(
    binary_target_summary
)

# Display target distribution by dataset source
source_target_table = pd.crosstab(
    heart_df["dataset"],
    heart_binary_target,
    margins=True
)

source_target_table.columns = [
    "No heart disease",
    "Heart disease present",
    "Total"
]

print(
    "Target distribution by dataset source:"
)

display(
    source_target_table
)

# Inspect all categorical feature values
categorical_columns = [
    "sex",
    "cp",
    "fbs",
    "restecg",
    "exang",
    "slope",
    "thal"
]

print(
    "Categorical feature values:"
)

for column in categorical_columns:
    print(
        f"\n{column}:"
    )

    print(
        heart_df[column]
        .value_counts(
            dropna=False
        )
    )

# Inspect numerical ranges and suspicious zero values
numerical_columns = [
    "age",
    "trestbps",
    "chol",
    "thalch",
    "oldpeak",
    "ca"
]

numerical_summary = pd.DataFrame(
    {
        "Minimum": (
            heart_df[
                numerical_columns
            ].min()
        ),
        "Maximum": (
            heart_df[
                numerical_columns
            ].max()
        ),
        "Mean": (
            heart_df[
                numerical_columns
            ].mean()
        ),
        "Missing Values": (
            heart_df[
                numerical_columns
            ].isnull().sum()
        ),
        "Zero Values": (
            heart_df[
                numerical_columns
            ].eq(0).sum()
        )
    }
)

print(
    "\nNumerical feature summary:"
)

display(
    numerical_summary.round(2)
)

Binary target distribution:

                       Count  Percentage
No heart disease         411       44.67
Heart disease present    509       55.33

Target distribution by dataset source:

               No heart disease  Heart disease present  Total
dataset
Cleveland                   165                    139    304
Hungary                     187                    106    293
Switzerland                   8                    115    123
VA Long Beach                51                    149    200
All                         411                    509    920

Categorical feature values:

sex:
sex
Male      726
Female    194
Name: count, dtype: int64

cp:
cp
asymptomatic       496
non-anginal        204
atypical angina    174
typical angina      46
Name: count, dtype: int64

fbs:
fbs
False    692
True     138
NaN       90
Name: count, dtype: int64

restecg:
restecg
normal              551
lv hypertrophy      188
st-t abnormality    179
NaN                   2
Name: count, dtype: int64

exang:
exang
False    528
True     337
NaN       55
Name: count, dtype: int64

slope:
slope
flat           345
NaN            309
upsloping      203
downsloping     63
Name: count, dtype: int64

thal:
thal
NaN                  486
normal               196
reversable defect    192
fixed defect          46
Name: count, dtype: int64

Numerical feature summary:

          Minimum  Maximum    Mean  Missing Values  Zero Values
age          28.0     77.0   53.51               0            0
trestbps      0.0    200.0  132.13              59            1
chol          0.0    603.0  199.13              30          172
thalch       60.0    202.0  137.55              55            0
oldpeak      -2.6      6.2    0.88              62          370
ca            0.0      3.0    0.68             611          181

In [4]:
# Create a working copy of the raw dataset
heart_clean = heart_df.copy()

# Create the binary target
heart_clean["heart_disease"] = (
    heart_clean["num"] > 0
).astype("int8")

# Remove the identifier and original multiclass target
heart_clean = heart_clean.drop(
    columns=[
        "id",
        "num"
    ]
)

# Replace medically impossible zero values with missing values
heart_clean["trestbps"] = (
    heart_clean["trestbps"]
    .replace(
        0,
        np.nan
    )
)

heart_clean["chol"] = (
    heart_clean["chol"]
    .replace(
        0,
        np.nan
    )
)

# Convert nullable boolean features to readable categories
boolean_mapping = {
    True: "Yes",
    False: "No"
}

for column in [
    "fbs",
    "exang"
]:
    heart_clean[column] = (
        heart_clean[column]
        .map(
            boolean_mapping
        )
    )

# Arrange the dataset columns
heart_clean = heart_clean[
    [
        "dataset",
        "age",
        "sex",
        "cp",
        "trestbps",
        "chol",
        "fbs",
        "restecg",
        "thalch",
        "exang",
        "oldpeak",
        "slope",
        "ca",
        "thal",
        "heart_disease"
    ]
]

# Build the processed dataset path
processed_data_path = (
    project_root
    / "data"
    / "processed"
    / "heart_disease_clean.csv"
)

# Save the cleaned dataset without imputing missing values
heart_clean.to_csv(
    processed_data_path,
    index=False
)

# Verify the cleaned dataset
print(
    "Cleaned dataset shape:",
    heart_clean.shape
)

print(
    "\nMissing values after cleaning:"
)

print(
    heart_clean.isnull()
    .sum()
    .sort_values(
        ascending=False
    )
)

print(
    "\nTarget distribution:"
)

print(
    heart_clean[
        "heart_disease"
    ].value_counts()
    .sort_index()
)

print(
    "\nProcessed file saved:",
    processed_data_path.exists()
)

print(
    "Processed file path:",
    processed_data_path
)

display(
    heart_clean.head()
)

Cleaned dataset shape: (920, 15)

Missing values after cleaning:
ca               611
thal             486
slope            309
chol             202
fbs               90
oldpeak           62
trestbps          60
thalch            55
exang             55
restecg            2
sex                0
cp                 0
dataset            0
age                0
heart_disease      0
dtype: int64

Target distribution:
heart_disease
0    411
1    509
Name: count, dtype: int64

Processed file saved: True
Processed file path: d:\1. My Files in Collage\5th Level\AI\Multi_Disease_ML_System\data\processed\heart_disease_clean.csv

,dataset,age,sex,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,heart_disease
0,Cleveland,63,Male,typical angina,145.0,233.0,Yes,lv hypertrophy,150.0,No,2.3,downsloping,0.0,fixed defect,0
1,Cleveland,67,Male,asymptomatic,160.0,286.0,No,lv hypertrophy,108.0,Yes,1.5,flat,3.0,normal,1
2,Cleveland,67,Male,asymptomatic,120.0,229.0,No,lv hypertrophy,129.0,Yes,2.6,flat,2.0,reversable defect,1
3,Cleveland,37,Male,non-anginal,130.0,250.0,No,normal,187.0,No,3.5,downsloping,0.0,normal,0
4,Cleveland,41,Female,atypical angina,130.0,204.0,No,lv hypertrophy,172.0,No,1.4,upsloping,0.0,normal,0